[common]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = generic_rp2350
board_build.core = earlephilhower
framework = arduino
monitor_speed = 115200
lib_deps = symlink://../

[env:phase1]
extends = common
build_flags = -std=gnu++17 -DENABLE_LOOP_TIMING -DPHASE=1

[env:phase2]
extends = common
build_flags = -std=gnu++17 -DENABLE_LOOP_TIMING -DPHASE=2

[env:phase3]
extends = common
build_flags = -std=gnu++17 -DENABLE_LOOP_TIMING -DPHASE=3

[env:phase4]
extends = common
build_flags = -std=gnu++17 -DENABLE_LOOP_TIMING -DPHASE=4
